// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using matamata.Data;

namespace matamata.Migrations
{
    [DbContext(typeof(matamataContext))]
    partial class matamataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("matamata.Models.Partida", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Gols1")
                        .HasColumnType("int");

                    b.Property<int>("Gols2")
                        .HasColumnType("int");

                    b.Property<int>("Penaltis1")
                        .HasColumnType("int");

                    b.Property<int>("Penaltis2")
                        .HasColumnType("int");

                    b.Property<int?>("Time1Id")
                        .HasColumnType("int");

                    b.Property<int?>("Time2Id")
                        .HasColumnType("int");

                    b.Property<int?>("TorneioId")
                        .HasColumnType("int");

                    b.Property<int?>("VencedorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Time1Id");

                    b.HasIndex("Time2Id");

                    b.HasIndex("TorneioId");

                    b.HasIndex("VencedorId");

                    b.ToTable("Partida");
                });

            modelBuilder.Entity("matamata.Models.Time", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TorneioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TorneioId");

                    b.ToTable("Time");
                });

            modelBuilder.Entity("matamata.Models.Torneio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("Id");

                    b.ToTable("Torneio");
                });

            modelBuilder.Entity("matamata.Models.Partida", b =>
                {
                    b.HasOne("matamata.Models.Time", "Time1")
                        .WithMany()
                        .HasForeignKey("Time1Id");

                    b.HasOne("matamata.Models.Time", "Time2")
                        .WithMany()
                        .HasForeignKey("Time2Id");

                    b.HasOne("matamata.Models.Torneio", null)
                        .WithMany("Partidas")
                        .HasForeignKey("TorneioId");

                    b.HasOne("matamata.Models.Time", "Vencedor")
                        .WithMany()
                        .HasForeignKey("VencedorId");
                });

            modelBuilder.Entity("matamata.Models.Time", b =>
                {
                    b.HasOne("matamata.Models.Torneio", null)
                        .WithMany("Times")
                        .HasForeignKey("TorneioId");
                });
#pragma warning restore 612, 618
        }
    }
}
